// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqhaosnpnmohrwfairwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxaGFvc25wbm1vaHJ3ZmFpcndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDgyMjksImV4cCI6MjA2NDYyNDIyOX0.U2O3gf4iEeagjVakyoisbKoAi5gOmq1-RwOLvN3vAfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);